# version: '3.8'

services:
  web:
    image: andersbremnes/newsrecsurvey:latest
    build: .
    container_name: NEWSREC-WEB
    platform: linux/amd64
    volumes:
      - static_volume:/app/staticfiles
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python3 manage.py wait_for_db &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py collectstatic --no-input &&
      gunicorn NEWSREC_survey.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - django_network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: NEWSREC-DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - django_network

  nginx:
    image: nginx:latest
    container_name: NEWSREC-NGINX
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - django_network
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

networks:
  django_network:
    driver: bridge
