# Generated by Django 4.2.16 on 2024-11-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News_article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aid", models.CharField(max_length=512, null=True)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("image_url", models.URLField()),
                ("date", models.DateField(blank=True, null=True)),
                ("article_url", models.URLField()),
                ("category", models.CharField(blank=True, max_length=512, null=True)),
                ("text", models.CharField(max_length=100000)),
                ("style", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "manipulated_title",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Personal_info",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.CharField(default=None, max_length=100)),
                ("name", models.CharField(default=None, max_length=50, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("headline_style", models.CharField(max_length=200, null=True)),
                ("manipulated_headlines", models.TextField(default="{}")),
                (
                    "selected_articles_list",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                ("score", models.IntegerField(default=0)),
                (
                    "preferred_headline",
                    models.CharField(
                        choices=[
                            (
                                "Forward reference",
                                "Kinas Økonomiske Fremtid: Usikkerheten som Følger Etter Gullalderen",
                            ),
                            (
                                "Metaphor",
                                "Kinas Økonomiske Skute i Uvær: Rentekutt som Redningsflåte",
                            ),
                            (
                                "Question",
                                "Er Kinas økonomiske gullalder over for godt?",
                            ),
                        ],
                        default=None,
                        max_length=200,
                        verbose_name="preferred_headline",
                    ),
                ),
                (
                    "preferred_headline2",
                    models.CharField(
                        choices=[
                            (
                                "Forward reference",
                                "Denne appen endrer måten nordmenn handler mat på",
                            ),
                            (
                                "Metaphor",
                                "Frifor: Navigatoren i Ultrabehandlet Matens Labyrint",
                            ),
                            (
                                "Question",
                                "Kan En App Revolusjonere Måten Vi Velger Mat På?",
                            ),
                        ],
                        default=None,
                        max_length=200,
                        verbose_name="preferred_headline2",
                    ),
                ),
                (
                    "preferred_headline3",
                    models.CharField(
                        choices=[
                            (
                                "Forward reference",
                                "Se prisforskjellen som overrasker mellom EX90 og XC90",
                            ),
                            (
                                "Metaphor",
                                "Fra Dinosaur til Lyn: Volvos Elektriske Revolusjon Ruller Inn",
                            ),
                            (
                                "Question",
                                "Kan Volvos EX90 virkelig spare deg for 293.000 kroner?",
                            ),
                        ],
                        default=None,
                        max_length=200,
                        verbose_name="preferred_headline3",
                    ),
                ),
            ],
            options={
                "verbose_name": "personal_info",
                "db_table": "personal_info",
                "ordering": ["id"],
            },
        ),
    ]
